import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import axios from 'axios';

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || `http://${window.location.hostname}:8081/api/v1` });
type Folder = { id: number; name: string; path: string; parentId?: number | null; _count?: { files: number; children: number } };
type FileItem = { id: number; originalFilename: string; mimeType?: string; size: number; createdAt: string; folder?: Folder | null };
const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
const size = (value: number) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`;
const icon = (file: FileItem) => file.mimeType?.startsWith('image') ? 'IMG' : file.mimeType?.includes('pdf') ? 'PDF' : file.mimeType?.includes('spreadsheet') ? 'XLS' : 'FILE';
const copyText = async (value: string) => { try { await navigator.clipboard.writeText(value); return true; } catch { const input = document.createElement('textarea'); input.value = value; input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.focus(); input.select(); const copied = document.execCommand('copy'); document.body.removeChild(input); return copied; } };

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('mbg_token'));
  const [user, setUser] = useState<any>(null);
  const [files, setFiles] = useState<FileItem[]>([]);
  const [folders, setFolders] = useState<Folder[]>([]);
  const [folderId, setFolderId] = useState<number | null>(null);
  const [query, setQuery] = useState('');
  const [view, setView] = useState<'list' | 'grid'>('list');
  const [selected, setSelected] = useState<FileItem | null>(null);
  const [folderDialog, setFolderDialog] = useState(false);
  const [folderName, setFolderName] = useState('');
  const [login, setLogin] = useState({ username: 'admin', password: 'admin123' });
  const [message, setMessage] = useState('');
  const [shareUrl, setShareUrl] = useState('');
  const fileInput = useRef<HTMLInputElement>(null);
  const headers = token ? auth(token) : {};
  const currentFolder = folders.find((folder) => folder.id === folderId);
  const visibleFolders = folders.filter((folder) => (folder.parentId || null) === folderId);
  const breadcrumbs = currentFolder ? currentFolder.path.split('/') : [];
  const folderTree = (parentId: number | null = null, depth = 0): ReactNode[] => folders.filter((folder) => (folder.parentId || null) === parentId).map((folder) => <div key={folder.id}><button className={folder.id === folderId ? 'nav-item active' : 'nav-item'} style={{ paddingLeft: `${10 + depth * 16}px` }} onClick={() => setFolderId(folder.id)}><span className="folder-icon">{depth ? '└' : '▰'}</span>{folder.name}<b>{folder._count?.files || ''}</b></button>{folderTree(folder.id, depth + 1)}</div>);

  const load = async () => { if (!token) return; const [fileResponse, folderResponse] = await Promise.all([api.get('/files', { headers, params: { ...(folderId ? { folderId } : {}), ...(query ? { q: query } : {}) } }), api.get('/folders', { headers })]); setFiles(fileResponse.data); setFolders(folderResponse.data); };
  useEffect(() => { load().catch((error) => setMessage(error.response?.data?.message || 'Gagal memuat workspace')); }, [token, folderId, query]);
  const totalFiles = folders.reduce((sum, folder) => sum + (folder._count?.files || 0), 0) + files.length;
  const loginSubmit = async (event: FormEvent) => { event.preventDefault(); try { const response = await api.post('/auth/login', login); localStorage.setItem('mbg_token', response.data.access_token); setToken(response.data.access_token); setUser(response.data.user); } catch { setMessage('Username atau password salah.'); } };
  const upload = async (list: FileList | null) => { if (!list || !token) return; for (const file of Array.from(list)) { const body = new FormData(); body.append('file', file); if (folderId) body.append('folderId', String(folderId)); await api.post('/files', body, { headers }); } if (fileInput.current) fileInput.current.value = ''; setMessage(`${list.length} file berhasil diupload.`); load(); };
  const createFolder = async (event: FormEvent) => { event.preventDefault(); await api.post('/folders', { name: folderName, parentId: folderId }, { headers }); setFolderName(''); setFolderDialog(false); setMessage('Folder berhasil dibuat.'); load(); };
  const rename = async () => { if (!selected) return; const name = window.prompt('Nama baru', selected.originalFilename); if (name) { await api.patch(`/files/${selected.id}`, { name }, { headers }); setSelected(null); load(); } };
  const share = async () => { if (!selected) return; const response = await api.post(`/files/${selected.id}/share`, {}, { headers }); const url = response.data.shareUrl; const copied = await copyText(url); setShareUrl(url); setMessage(copied ? 'Link publik berhasil disalin.' : 'Link siap digunakan. Klik Pilih URL lalu tekan Ctrl+C.'); };
  const remove = async () => { if (!selected || !window.confirm(`Hapus ${selected.originalFilename}?`)) return; await api.delete(`/files/${selected.id}`, { headers }); setSelected(null); setMessage('File dihapus.'); load(); };
  const download = async (file: FileItem) => { const response = await api.get(`/files/${file.id}/download`, { headers, responseType: 'blob' }); const link = document.createElement('a'); link.href = URL.createObjectURL(response.data); link.download = file.originalFilename; link.click(); URL.revokeObjectURL(link.href); };

  if (!token) return <main className="login"><section className="login-card"><p className="eyebrow">MBG FILE MANAGEMENT</p><h1>Semua aset,<br /><em>di satu tempat.</em></h1><p className="muted">Workspace internal untuk mengatur dokumen, backup, dan data proyek MBG.</p><form onSubmit={loginSubmit}><label>Username<input value={login.username} onChange={(e) => setLogin({ ...login, username: e.target.value })} /></label><label>Password<input type="password" value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })} /></label>{message && <p className="form-error">{message}</p>}<button>Masuk ke workspace</button></form><small>Development: admin / admin123</small></section></main>;
  return <main className="shell">
     <aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><span>MBG <small>FILES</small></span></div><button className="new-button" onClick={() => fileInput.current?.click()}>＋ Upload file</button><input ref={fileInput} hidden type="file" multiple onChange={(e) => upload(e.target.files)} /><nav><p className="nav-label">WORKSPACE</p><button className={!folderId ? 'nav-item active' : 'nav-item'} onClick={() => setFolderId(null)}><span>◈</span> Semua file <b>{totalFiles}</b></button><button className="nav-item" onClick={() => setFolderDialog(true)}><span>＋</span> Folder baru</button><p className="nav-label folder-label">FOLDER</p>{folderTree()}</nav><div className="storage"><div className="storage-head"><span>STORAGE</span><b>—</b></div><div className="storage-line"><i /></div><p>Storage lokal<br /><strong>Tanpa batas</strong></p></div><div className="sidebar-foot">MBG File Manager<br /><span>v1.0 · Internal</span></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="eyebrow">FILE MANAGEMENT PLATFORM</p><h1>Workspace files</h1></div><div className="profile"><span className="online" /> Terhubung <span className="avatar">{user?.name?.[0] || 'A'}</span><button className="logout" onClick={() => { localStorage.removeItem('mbg_token'); setToken(null); }}>Keluar</button></div></header>
      <div className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari file atau folder..." /></label><button className="icon-button" onClick={() => load()} title="Muat ulang">↻</button><div className="view-buttons"><button className={view === 'list' ? 'chosen' : ''} onClick={() => setView('list')}>☷</button><button className={view === 'grid' ? 'chosen' : ''} onClick={() => setView('grid')}>⊞</button></div><button className="primary" onClick={() => fileInput.current?.click()}>Upload file <span>↑</span></button></div>
       <div className="breadcrumb"><button onClick={() => setFolderId(null)}>Semua file</button>{breadcrumbs.map((crumb, index) => <span key={`${crumb}-${index}`}> / {crumb}</span>)}</div>{message && <div className="notice">✓ {message}{shareUrl && <span className="share-link"><input readOnly value={shareUrl} onFocus={(event) => event.currentTarget.select()} aria-label="URL share" /><a href={shareUrl} target="_blank" rel="noreferrer">Buka link</a><button onClick={async () => { const copied = await copyText(shareUrl); setMessage(copied ? 'Link berhasil disalin. Silakan tekan Ctrl+V di tujuan.' : 'Pilih URL, lalu tekan Ctrl+C.'); }}>Salin</button><button onClick={() => { const input = document.querySelector<HTMLInputElement>('.share-link input'); input?.focus(); input?.select(); setMessage('URL sudah dipilih. Tekan Ctrl+C lalu Ctrl+V di tujuan.'); }}>Pilih URL</button></span>}<button onClick={() => { setMessage(''); setShareUrl(''); }}>×</button></div>}
      <div className="section-title"><div><h2>{currentFolder?.name || 'Semua file'}</h2><p className="muted">{files.length} file · {visibleFolders.length} folder</p></div>{selected && <div className="selection-actions"><strong>{selected.originalFilename}</strong><button onClick={share}>Share link</button><button onClick={rename}>Rename</button><button onClick={remove}>Hapus</button><button onClick={() => setSelected(null)}>×</button></div>}</div>
      <div className={view === 'grid' ? 'items grid-view' : 'items'}>{visibleFolders.map((folder) => <button className="folder-card" key={folder.id} onDoubleClick={() => setFolderId(folder.id)} onClick={() => setFolderId(folder.id)}><span className="large-folder">▰</span><span><b>{folder.name}</b><small>{folder._count?.files || 0} file</small></span><i>•••</i></button>)}{files.map((file) => <article className={selected?.id === file.id ? 'file-card selected' : 'file-card'} key={file.id} onClick={() => setSelected(file)}><span className="file-type">{icon(file)}</span><div className="file-main"><b>{file.originalFilename}</b><small>{file.mimeType || 'File'} · {size(file.size)}</small></div><span className="file-date">{new Date(file.createdAt).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}</span><button className="download" onClick={(event) => { event.stopPropagation(); download(file); }}>↓</button></article>)}{!files.length && !visibleFolders.length && <div className="empty"><span>□</span><b>Folder ini masih kosong</b><small>Upload file atau buat folder baru untuk mulai mengatur workspace.</small></div>}</div>
      <footer>Tip: klik folder untuk membukanya · klik file untuk melihat aksi</footer>
    </section>{folderDialog && <div className="modal-backdrop"><form className="modal" onSubmit={createFolder}><button type="button" className="modal-close" onClick={() => setFolderDialog(false)}>×</button><p className="eyebrow">FOLDER BARU</p><h2>Buat folder</h2><p className="muted">Folder akan dibuat di {currentFolder?.name || 'root workspace'}.</p><label>Nama folder<input autoFocus value={folderName} onChange={(e) => setFolderName(e.target.value)} placeholder="Contoh: Dokumen HR" /></label><div className="modal-actions"><button type="button" className="quiet" onClick={() => setFolderDialog(false)}>Batal</button><button disabled={!folderName.trim()}>Buat folder</button></div></form></div>}
  </main>;
}
